[build]
  # Diretório base do projeto
  base = "client"
  
  # Comando de build com verificação de ambiente
  command = "npm run build:netlify:safe"
  
  # Diretório de saída
  publish = "dist"
  
  # Variáveis de ambiente obrigatórias
  [build.environment]
    NODE_ENV = "production"
    NODE_VERSION = "18"

# Verificação de variáveis de ambiente antes do build
[[build.processing]]
  skip_processing = false

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://enso-backend-0aa1.onrender.com https://smvohmdytczfouslcaju.supabase.co wss://enso-backend-0aa1.onrender.com;"

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers específicos para arquivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers para manifest
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configurações de build específicas
[build.processing]
  skip_processing = false

# Plugin para verificação de variáveis de ambiente
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Configurações de deploy
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configurações de função (se necessário)
[functions]
  directory = "netlify/functions"

# Configurações de edge functions (se necessário)
[edge_functions]
  directory = "netlify/edge-functions"
