services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: enso_postgres
    environment:
      POSTGRES_DB: enso_db
      POSTGRES_USER: enso_db
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - enso_network
    restart: unless-stopped

  # Enso Application
  controlflow:
    build:
      context: .
      target: development
    container_name: enso_app
    environment:
      DATABASE_URL: postgresql://enso_db:123@postgres:5432/enso_db
      JWT_SECRET: enso-jwt-secret-key-2024-development
      SESSION_SECRET: enso-session-secret-2024
      PORT: 5002
      NODE_ENV: development
      UPLOAD_DIR: ./uploads
      MAX_FILE_SIZE: 10485760
      LOG_LEVEL: info
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
      - ./shared:/app/shared
      - ./migrations:/app/migrations
      - ./server:/app/server
    networks:
      - enso_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  enso_network:
    driver: bridge
