services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: test_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network
    restart: unless-stopped

  # Frontend React (Teste)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    container_name: test_frontend
    environment:
      VITE_API_URL: http://localhost:5002
      VITE_SUPABASE_URL: https://smvohmdytczfouslcaju.supabase.co
      VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdm9obWR5dGN6Zm91c2xjYWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTk1MzQsImV4cCI6MjA3MTA5NTUzNH0.0qJpEQVooxEDsRa26MhqDk76ACb7Tg-Qutswoegdk7U
      VITE_WEBSOCKET_URL: ws://localhost:5002
      NODE_ENV: development
      VITE_NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
      - ./client/vite.config.ts:/app/vite.config.ts
      - ./client/tsconfig.json:/app/tsconfig.json
      - ./client/tailwind.config.ts:/app/tailwind.config.ts
      - ./client/postcss.config.js:/app/postcss.config.js
      - ./client/index.html:/app/index.html
      - ./client/env.local:/app/.env.local
    networks:
      - test_network
    restart: unless-stopped

volumes:
  postgres_test_data:
    driver: local

networks:
  test_network:
    driver: bridge
