services:
  - type: web
    name: enso-backend
    env: node
    plan: starter
    buildCommand: npm install && node scripts/build-production.js
    startCommand: cd dist && npm install --production && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://enso-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    repo: https://github.com/davidalss/ControlFlow
    rootDir: server
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 3
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /api/*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
      - path: /api/*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With"

  - type: web
    name: enso-frontend
    env: static
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://enso-backend-0aa1.onrender.com
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    autoDeploy: true
    branch: main
    repo: https://github.com/davidalss/ControlFlow
    rootDir: client
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /index.html
        name: Cache-Control
        value: "public, max-age=0, must-revalidate"
