services:
  - type: web
    name: enso-backend
    env: node
    plan: starter
    buildCommand: npm install && node scripts/build-production.js
    startCommand: cd dist && npm install --production && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    repo: https://github.com/davidalss/ControlFlow
    rootDir: server
